# Generated by Django 5.1.1 on 2024-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
